# Generated by Django 3.1.2 on 2020-12-03 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comment',
            new_name='Contact',
        ),
    ]
